### PR TITLE
Adding some steps for installation

### PR DESCRIPTION
**Pull request by mafairnet**

### CODE REVIEW

**Comment by mafairnet** [comment]
Edit this:
...
cd /usr/src/
wget https://github.com/mafairnet/datadog-asteriskpbx/archive/master.zip
unzip master.zip
...
To this
..
cd /usr/src/
wget https://github.com/jwestbrook/datadog-asteriskpbx/archive/master.zip
unzip master.zip
..

I left that line to other workmates to update some files.

**Comment by jwestbrook** [comment]
Thanks for all your work on this.

I've stopped using Datadog because the cost is too high and I'm running my own CollectD/StatsD server - if you want this repo we can do a transfer and you can continue running it.

**Comment by mafairnet** [comment]
I'd love to continue the work with the repo I'd be pleased if you transfer me the repo.

**Comment by jwestbrook** [comment]
It won't let me transfer the repo to you - you already have a fork of it. I can rename this one or you can rename yours. Your choice.

I'll merge this pull request first though

**Comment by mafairnet** [comment]
Ok, I'll rename mine.

Thank you for everything, this module was helpfull to me a lot.

**Comment by jwestbrook** [comment]
Its not letting me transfer the repo to you - I added you as a collaborator so you can do whatever you need to.

I think its because your fork still exists /shrug

**Pull request merged**
